name: service_app
description: Shadow service app.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.0
  crclib: ^3.0.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  injectable: ^1.5.3
  path_provider: ^2.0.11
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  flutter_secure_storage: ^5.0.2
  either_dart: ^0.3.0
  geolocator: ^9.0.2
  file_picker: ^5.2.9
  local_auth: ^2.1.6
  passcode_screen: ^2.0.1
  intl_phone_number_input: ^0.7.3+1
  bluetooth_package:
    path: packages/bluetooth_package
  pinput: ^2.2.16
  #firebase_core: ^2.1.0
  easy_container: ^1.0.4
  #firebase_phone_auth_handler: ^1.0.8
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.1.0
  #firebase_database: ^10.1.1
  flutter_logs: ^2.1.10
  flutter_svg: ^2.0.7
  #firebase_storage: ^11.2.6
  intl: ^0.18.1
  rest_client: ^2.2.3+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.2.0
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - 'assets/logo_white.png'
    - 'assets/json_log_failtures.json'


