name: bluetooth_package
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+16

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  either_dart: ^0.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_blue_plus:
    git:
      url: https://github.com/crazy-rodney/flutter_blue_plus
  freezed_annotation: ^2.0.3
  geolocator: ^9.0.2
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  rxdart: ^0.27.7
  synchronized: ^3.0.0+2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        default_package: bluetooth_package
      ios:
        default_package: bluetooth_package
